### ISSUE TITLE
Package httpx for deployment, it only on conda-forge right now.

### ISSUE THREAD

**Issue by ke-zhang-rd** [NSLS-II/pyolog2#13]

**Comment by ke-zhang-rd** [comment]
This is solved by https://github.com/nsls-ii-forge/httpx-feedstock.

**Comment by mrakitin** [comment]
The noarch package can be found here: https://anaconda.org/nsls2forge/httpx/files.
![image](https://user-images.githubusercontent.com/13209176/81955103-afe8d380-95d7-11ea-812b-69aa2db296e4.png)
