### ISSUE TITLE
Update README.

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/pyolog2#16]
- [x] The first sentence ("This is intended to be a simpler Python client to the Olog,") reflects our original goal to write an alternative python client to the old Olog, but this project has actually evolved into being the official Python client to the _new_ rewritten Olog. What is the name of this "new Olog"? Can we link to it?
- [x] The installation instructions need to be updated since `test-requirements.txt` has been renamed to `requirements-dev.txt`.
- [x] The "General Case" currently advises using `docker-compose` to run an old Olog server. The contents of this section should be removed and replaced with something like "TO DO: Document how to stand up a new Olog server for testing."

**Comment by ke-zhang-rd** [comment]
close by #17
